import type { SoftUIIconMap } from "../slots"
import {
  RiAddCircleFill,
  RiAddLine,
  RiAiGenerate3dLine,
  RiAlignCenter,
  RiAlignLeft,
  RiAlignRight,
  RiAppsFill,
  RiArrowDownSLine,
  RiArrowLeftLine,
  RiArrowLeftSLine,
  RiArrowRightLine,
  RiArrowRightSLine,
  RiArrowUpSLine,
  RiBankCardFill,
  RiBankFill,
  RiBold,
  RiBookmarkFill,
  RiBookmarkLine,
  RiCheckboxCircleFill,
  RiCheckFill,
  RiCheckLine,
  RiCloseCircleFill,
  RiCloseLine,
  RiContrast2Fill,
  RiCustomerService2Fill,
  RiDeleteBinFill,
  RiDeleteBinLine,
  RiDraftFill,
  RiErrorWarningFill,
  RiExpandUpDownLine,
  RiEyeLine,
  RiEyeOffLine,
  RiFileCopyFill,
  RiFileCopyLine,
  RiHashtag,
  RiHeartFill,
  RiHeartLine,
  RiHome7Fill,
  RiInformationFill,
  RiInputMethodFill,
  RiItalic,
  RiLayoutLeftFill,
  RiLightbulbAiFill,
  RiLoader2Line,
  RiLoader4Line,
  RiMenuLine,
  RiMenuSearchLine,
  RiMoonFill,
  RiMoonLine,
  RiMoreLine,
  RiNotificationLine,
  RiNotificationOffLine,
  RiPaletteFill,
  RiPriceTag3Fill,
  RiQuestionFill,
  RiSearchLine,
  RiSettings6Fill,
  RiSpam2Fill,
  RiSpamFill,
  RiStarFill,
  RiStarLine,
  RiStickyNoteFill,
  RiSubtractFill,
  RiSubtractLine,
  RiSunFill,
  RiSunLine,
  RiSwapFill,
  RiThumbUpFill,
  RiThumbUpLine,
  RiUnderline,
  RiUploadCloud2Line,
  RiUserAddFill,
  RiUserFill,
  RiVolumeMuteFill,
  RiVolumeMuteLine,
  RiVolumeUpFill,
  RiVolumeUpLine,
} from "@remixicon/react"

export const defaultSoftUIIcons: SoftUIIconMap = {
  AddCircleIcon: RiAddCircleFill,
  AddIcon: RiAddLine,
  AiGenerate3dIcon: RiAiGenerate3dLine,
  AlignCenterIcon: RiAlignCenter,
  AlignLeftIcon: RiAlignLeft,
  AlignRightIcon: RiAlignRight,
  AppsFillIcon: RiAppsFill,
  ArrowDownIcon: RiArrowDownSLine,
  ArrowLeftIcon: RiArrowLeftLine,
  ArrowRightIcon: RiArrowRightLine,
  ArrowUpIcon: RiArrowUpSLine,
  BankCardIcon: RiBankCardFill,
  BankIcon: RiBankFill,
  BoldIcon: RiBold,
  BookmarkFillIcon: RiBookmarkFill,
  BookmarkIcon: RiBookmarkLine,
  CheckCircleIcon: RiCheckboxCircleFill,
  CheckIcon: RiCheckLine,
  CloseIcon: RiCloseLine,
  ContrastFillIcon: RiContrast2Fill,
  CopyFillIcon: RiFileCopyFill,
  CopyIcon: RiFileCopyLine,
  CustomerServiceIcon: RiCustomerService2Fill,
  DraftFillIcon: RiDraftFill,
  ExpandUpDownIcon: RiExpandUpDownLine,
  EyeIcon: RiEyeLine,
  EyeOffIcon: RiEyeOffLine,
  HashtagIcon: RiHashtag,
  HeartFillIcon: RiHeartFill,
  HeartIcon: RiHeartLine,
  HomeIcon: RiHome7Fill,
  InformationFillIcon: RiInformationFill,
  InputMethodIcon: RiInputMethodFill,
  ItalicIcon: RiItalic,
  LayoutLeftIcon: RiLayoutLeftFill,
  LightbulbAiFillIcon: RiLightbulbAiFill,
  LoaderIcon: RiLoader4Line,
  MenuIcon: RiMenuLine,
  MenuSearchLineIcon: RiMenuSearchLine,
  MoonFillIcon: RiMoonFill,
  MoonIcon: RiMoonLine,
  MuteFillIcon: RiVolumeMuteFill,
  MuteIcon: RiVolumeMuteLine,
  NotificationIcon: RiNotificationLine,
  NotificationOffIcon: RiNotificationOffLine,
  PaletteIcon: RiPaletteFill,
  PriceTagIcon: RiPriceTag3Fill,
  QuestionIcon: RiQuestionFill,
  RiAddCircleFill: RiAddCircleFill,
  RiAddLine: RiAddLine,
  RiAiGenerate3dLine: RiAiGenerate3dLine,
  RiAlignCenter: RiAlignCenter,
  RiAlignLeft: RiAlignLeft,
  RiAlignRight: RiAlignRight,
  RiAppsFill: RiAppsFill,
  RiArrowDownSLine: RiArrowDownSLine,
  RiArrowLeftLine: RiArrowLeftLine,
  RiArrowLeftSLine: RiArrowLeftSLine,
  RiArrowRightLine: RiArrowRightLine,
  RiArrowRightSLine: RiArrowRightSLine,
  RiArrowUpSLine: RiArrowUpSLine,
  RiBankCardFill: RiBankCardFill,
  RiBankFill: RiBankFill,
  RiBold: RiBold,
  RiBookmarkFill: RiBookmarkFill,
  RiBookmarkLine: RiBookmarkLine,
  RiCheckboxCircleFill: RiCheckboxCircleFill,
  RiCheckFill: RiCheckFill,
  RiCheckLine: RiCheckLine,
  RiCloseCircleFill: RiCloseCircleFill,
  RiCloseLine: RiCloseLine,
  RiContrast2Fill: RiContrast2Fill,
  RiCustomerService2Fill: RiCustomerService2Fill,
  RiDeleteBinFill: RiDeleteBinFill,
  RiDeleteBinLine: RiDeleteBinLine,
  RiDraftFill: RiDraftFill,
  RiErrorWarningFill: RiErrorWarningFill,
  RiExpandUpDownLine: RiExpandUpDownLine,
  RiEyeLine: RiEyeLine,
  RiEyeOffLine: RiEyeOffLine,
  RiFileCopyFill: RiFileCopyFill,
  RiFileCopyLine: RiFileCopyLine,
  RiHashtag: RiHashtag,
  RiHeartFill: RiHeartFill,
  RiHeartLine: RiHeartLine,
  RiHome7Fill: RiHome7Fill,
  RiInformationFill: RiInformationFill,
  RiInputMethodFill: RiInputMethodFill,
  RiItalic: RiItalic,
  RiLayoutLeftFill: RiLayoutLeftFill,
  RiLightbulbAiFill: RiLightbulbAiFill,
  RiLoader2Line: RiLoader2Line,
  RiLoader4Line: RiLoader4Line,
  RiMenuLine: RiMenuLine,
  RiMenuSearchLine: RiMenuSearchLine,
  RiMoonFill: RiMoonFill,
  RiMoonLine: RiMoonLine,
  RiMoreLine: RiMoreLine,
  RiNotificationLine: RiNotificationLine,
  RiNotificationOffLine: RiNotificationOffLine,
  RiPaletteFill: RiPaletteFill,
  RiPriceTag3Fill: RiPriceTag3Fill,
  RiQuestionFill: RiQuestionFill,
  RiSearchLine: RiSearchLine,
  RiSettings6Fill: RiSettings6Fill,
  RiSpam2Fill: RiSpam2Fill,
  RiSpamFill: RiSpamFill,
  RiStarFill: RiStarFill,
  RiStarLine: RiStarLine,
  RiStickyNoteFill: RiStickyNoteFill,
  RiSubtractFill: RiSubtractFill,
  RiSubtractLine: RiSubtractLine,
  RiSunFill: RiSunFill,
  RiSunLine: RiSunLine,
  RiSwapFill: RiSwapFill,
  RiThumbUpFill: RiThumbUpFill,
  RiThumbUpLine: RiThumbUpLine,
  RiUnderline: RiUnderline,
  RiUploadCloud2Line: RiUploadCloud2Line,
  RiUserAddFill: RiUserAddFill,
  RiUserFill: RiUserFill,
  RiVolumeMuteFill: RiVolumeMuteFill,
  RiVolumeMuteLine: RiVolumeMuteLine,
  RiVolumeUpFill: RiVolumeUpFill,
  RiVolumeUpLine: RiVolumeUpLine,
  SearchIcon: RiSearchLine,
  SettingsIcon: RiSettings6Fill,
  Spam2FillIcon: RiSpam2Fill,
  SpamFillIcon: RiSpamFill,
  StarFillIcon: RiStarFill,
  StarIcon: RiStarLine,
  StickyNoteFillIcon: RiStickyNoteFill,
  SunFillIcon: RiSunFill,
  SunIcon: RiSunLine,
  SwapIcon: RiSwapFill,
  ThumbUpFillIcon: RiThumbUpFill,
  ThumbUpIcon: RiThumbUpLine,
  TrashIcon: RiDeleteBinFill,
  UnderlineIcon: RiUnderline,
  UserAddIcon: RiUserAddFill,
  VolumeFillIcon: RiVolumeUpFill,
  VolumeIcon: RiVolumeUpLine,
}
